//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/miskr/TKiK/TKiK_repozytorium/Grammars/C_Grammar.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CGrammar {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IC_GrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class C_GrammarBaseListener : IC_GrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] C_GrammarParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] C_GrammarParser.StartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.translationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTranslationUnit([NotNull] C_GrammarParser.TranslationUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.translationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTranslationUnit([NotNull] C_GrammarParser.TranslationUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.hashStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHashStatement([NotNull] C_GrammarParser.HashStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.hashStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHashStatement([NotNull] C_GrammarParser.HashStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.undefStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUndefStatement([NotNull] C_GrammarParser.UndefStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.undefStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUndefStatement([NotNull] C_GrammarParser.UndefStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.ifdefStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfdefStatement([NotNull] C_GrammarParser.IfdefStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.ifdefStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfdefStatement([NotNull] C_GrammarParser.IfdefStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] C_GrammarParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] C_GrammarParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.elifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElifStatement([NotNull] C_GrammarParser.ElifStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.elifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElifStatement([NotNull] C_GrammarParser.ElifStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseStatement([NotNull] C_GrammarParser.ElseStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseStatement([NotNull] C_GrammarParser.ElseStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.ifndefStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfndefStatement([NotNull] C_GrammarParser.IfndefStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.ifndefStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfndefStatement([NotNull] C_GrammarParser.IfndefStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.endIfStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndIfStatement([NotNull] C_GrammarParser.EndIfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.endIfStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndIfStatement([NotNull] C_GrammarParser.EndIfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.defineStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefineStatement([NotNull] C_GrammarParser.DefineStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.defineStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefineStatement([NotNull] C_GrammarParser.DefineStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.includeStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncludeStatement([NotNull] C_GrammarParser.IncludeStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.includeStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncludeStatement([NotNull] C_GrammarParser.IncludeStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.libraryName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLibraryName([NotNull] C_GrammarParser.LibraryNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.libraryName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLibraryName([NotNull] C_GrammarParser.LibraryNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.externalDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExternalDeclaration([NotNull] C_GrammarParser.ExternalDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.externalDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExternalDeclaration([NotNull] C_GrammarParser.ExternalDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.functionDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDefinition([NotNull] C_GrammarParser.FunctionDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.functionDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDefinition([NotNull] C_GrammarParser.FunctionDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.jumpStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJumpStatement([NotNull] C_GrammarParser.JumpStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.jumpStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJumpStatement([NotNull] C_GrammarParser.JumpStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.iterationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIterationStatement([NotNull] C_GrammarParser.IterationStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.iterationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIterationStatement([NotNull] C_GrammarParser.IterationStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.selectionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelectionStatement([NotNull] C_GrammarParser.SelectionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.selectionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelectionStatement([NotNull] C_GrammarParser.SelectionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionStatement([NotNull] C_GrammarParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionStatement([NotNull] C_GrammarParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.statementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatementList([NotNull] C_GrammarParser.StatementListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.statementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatementList([NotNull] C_GrammarParser.StatementListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.declarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarationList([NotNull] C_GrammarParser.DeclarationListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.declarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarationList([NotNull] C_GrammarParser.DeclarationListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.compoundStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompoundStatement([NotNull] C_GrammarParser.CompoundStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.compoundStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompoundStatement([NotNull] C_GrammarParser.CompoundStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.blockItemList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockItemList([NotNull] C_GrammarParser.BlockItemListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.blockItemList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockItemList([NotNull] C_GrammarParser.BlockItemListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.blockItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockItem([NotNull] C_GrammarParser.BlockItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.blockItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockItem([NotNull] C_GrammarParser.BlockItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.labeledStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabeledStatement([NotNull] C_GrammarParser.LabeledStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.labeledStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabeledStatement([NotNull] C_GrammarParser.LabeledStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] C_GrammarParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] C_GrammarParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.initializerList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitializerList([NotNull] C_GrammarParser.InitializerListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.initializerList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitializerList([NotNull] C_GrammarParser.InitializerListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitializer([NotNull] C_GrammarParser.InitializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitializer([NotNull] C_GrammarParser.InitializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.directAbstractDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectAbstractDeclarator([NotNull] C_GrammarParser.DirectAbstractDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.directAbstractDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectAbstractDeclarator([NotNull] C_GrammarParser.DirectAbstractDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.abstractDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAbstractDeclarator([NotNull] C_GrammarParser.AbstractDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.abstractDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAbstractDeclarator([NotNull] C_GrammarParser.AbstractDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierList([NotNull] C_GrammarParser.IdentifierListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierList([NotNull] C_GrammarParser.IdentifierListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.parameterDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterDeclaration([NotNull] C_GrammarParser.ParameterDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.parameterDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterDeclaration([NotNull] C_GrammarParser.ParameterDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterList([NotNull] C_GrammarParser.ParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterList([NotNull] C_GrammarParser.ParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.typeQualifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeQualifierList([NotNull] C_GrammarParser.TypeQualifierListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.typeQualifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeQualifierList([NotNull] C_GrammarParser.TypeQualifierListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.pointer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointer([NotNull] C_GrammarParser.PointerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.pointer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointer([NotNull] C_GrammarParser.PointerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.directDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectDeclarator([NotNull] C_GrammarParser.DirectDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.directDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectDeclarator([NotNull] C_GrammarParser.DirectDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarator([NotNull] C_GrammarParser.DeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarator([NotNull] C_GrammarParser.DeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.specifierQualifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecifierQualifierList([NotNull] C_GrammarParser.SpecifierQualifierListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.specifierQualifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecifierQualifierList([NotNull] C_GrammarParser.SpecifierQualifierListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.structSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructSpecifier([NotNull] C_GrammarParser.StructSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.structSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructSpecifier([NotNull] C_GrammarParser.StructSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.structDeclarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDeclarationList([NotNull] C_GrammarParser.StructDeclarationListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.structDeclarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDeclarationList([NotNull] C_GrammarParser.StructDeclarationListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.structDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDeclaration([NotNull] C_GrammarParser.StructDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.structDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDeclaration([NotNull] C_GrammarParser.StructDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.structDeclaratorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDeclaratorList([NotNull] C_GrammarParser.StructDeclaratorListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.structDeclaratorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDeclaratorList([NotNull] C_GrammarParser.StructDeclaratorListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.structDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDeclarator([NotNull] C_GrammarParser.StructDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.structDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDeclarator([NotNull] C_GrammarParser.StructDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.storageClassSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStorageClassSpecifier([NotNull] C_GrammarParser.StorageClassSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.storageClassSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStorageClassSpecifier([NotNull] C_GrammarParser.StorageClassSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.typeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeSpecifier([NotNull] C_GrammarParser.TypeSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.typeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeSpecifier([NotNull] C_GrammarParser.TypeSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.typeNameIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeNameIdentifier([NotNull] C_GrammarParser.TypeNameIdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.typeNameIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeNameIdentifier([NotNull] C_GrammarParser.TypeNameIdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeName([NotNull] C_GrammarParser.TypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeName([NotNull] C_GrammarParser.TypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.declarationSpecifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarationSpecifiers([NotNull] C_GrammarParser.DeclarationSpecifiersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.declarationSpecifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarationSpecifiers([NotNull] C_GrammarParser.DeclarationSpecifiersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.initDeclaratorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitDeclaratorList([NotNull] C_GrammarParser.InitDeclaratorListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.initDeclaratorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitDeclaratorList([NotNull] C_GrammarParser.InitDeclaratorListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.initDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitDeclarator([NotNull] C_GrammarParser.InitDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.initDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitDeclarator([NotNull] C_GrammarParser.InitDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] C_GrammarParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] C_GrammarParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.constantExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstantExpression([NotNull] C_GrammarParser.ConstantExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.constantExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstantExpression([NotNull] C_GrammarParser.ConstantExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] C_GrammarParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] C_GrammarParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.assignmentOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentOperator([NotNull] C_GrammarParser.AssignmentOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.assignmentOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentOperator([NotNull] C_GrammarParser.AssignmentOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.assignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentExpression([NotNull] C_GrammarParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.assignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentExpression([NotNull] C_GrammarParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.conditionalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionalExpression([NotNull] C_GrammarParser.ConditionalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.conditionalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionalExpression([NotNull] C_GrammarParser.ConditionalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.logicalOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalOrExpression([NotNull] C_GrammarParser.LogicalOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.logicalOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalOrExpression([NotNull] C_GrammarParser.LogicalOrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.logicalAndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalAndExpression([NotNull] C_GrammarParser.LogicalAndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.logicalAndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalAndExpression([NotNull] C_GrammarParser.LogicalAndExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.equalityExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualityExpression([NotNull] C_GrammarParser.EqualityExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.equalityExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualityExpression([NotNull] C_GrammarParser.EqualityExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpression([NotNull] C_GrammarParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpression([NotNull] C_GrammarParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.additiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditiveExpression([NotNull] C_GrammarParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.additiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditiveExpression([NotNull] C_GrammarParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.multiplicativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicativeExpression([NotNull] C_GrammarParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.multiplicativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicativeExpression([NotNull] C_GrammarParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.castExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCastExpression([NotNull] C_GrammarParser.CastExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.castExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCastExpression([NotNull] C_GrammarParser.CastExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.unaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryOperator([NotNull] C_GrammarParser.UnaryOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.unaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryOperator([NotNull] C_GrammarParser.UnaryOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExpression([NotNull] C_GrammarParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExpression([NotNull] C_GrammarParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.argumentExpressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentExpressionList([NotNull] C_GrammarParser.ArgumentExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.argumentExpressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentExpressionList([NotNull] C_GrammarParser.ArgumentExpressionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.postfixExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfixExpression([NotNull] C_GrammarParser.PostfixExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.postfixExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfixExpression([NotNull] C_GrammarParser.PostfixExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="C_GrammarParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryExpression([NotNull] C_GrammarParser.PrimaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="C_GrammarParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryExpression([NotNull] C_GrammarParser.PrimaryExpressionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace CGrammar
